name: gptheresa
services:
    init-data:
        image: alpine
        container_name: init-data
        volumes:
            - ./gpt-sovits:/gpt-sovits
            - ./entrypoint.sh:/entrypoint.sh
        entrypoint: ["/bin/sh", "/entrypoint.sh"]
        command: ["sh", "-c", "echo 'Initialed sovits data.'"]
    openweb-ui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: openweb-ui
        environment:
            - WEBUI_AUTH=False
            - DATABASE_URL=sqlite:///app/backend/data/webui-docker.db
        ports:
            - "8080:8080"
        volumes:
            - ./openweb-ui:/app/backend/data
        restart: unless-stopped
    gpt-sovits-cpu:
        image: breakstring/gpt-sovits:latest
        container_name: gpt-sovits-cpu
        depends_on:
            init-data:
                condition: service_completed_successfully
        environment:
            - is_half=False
            - is_share=False
            - gpt_path=/gpt-sovits-data/GPT_weights/xiaote.ckpt
            - sovits_path=/gpt-sovits-data/SoVITS_weights/xiaote.pth
            - cnhubert_path=GPT_SoVITS/pretrained_models/chinese-hubert-base
            - bert_path=GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
        volumes:
            - ./gpt-sovits:/gpt-sovits-data
            - gpt-sovits-cpu-data-output:/workspace/output
            - gpt-sovits-cpu-data-logs:/workspace/logs
            - gpt-sovits-cpu-data-reference:/workspace/reference
        working_dir: /workspace
        ports:
            - "9872:9872"
        shm_size: 16G
        stdin_open: true
        tty: true
        command: ["python", "GPT_SoVITS/inference_webui.py", "zh"]
        restart: unless-stopped
    middleapi:
        build: 
            context: ./middleapi
            dockerfile: Dockerfile
        container_name: middleapi
        ports:
            - "8000:8000"
        depends_on:
            - ollama-cpu
            - openweb-ui
            - gpt-sovits-cpu
        restart: unless-stopped
volumes:
    gpt-sovits-cpu-data-output: {}
    gpt-sovits-cpu-data-logs: {}
    gpt-sovits-cpu-data-reference: {}