name: gptheresa
services:
    openweb-ui:
        image: ghcr.io/open-webui/open-webui:main
        container_name: openweb-ui
        environment:
            - WEBUI_AUTH=False
        ports:
            - "8080:8080"
        volumes:
            - ./openweb-ui:/app/backend/data
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: "all"
                          capabilities: [gpu]
        restart: unless-stopped
    gpt-sovits:
        image: breakstring/gpt-sovits:latest
        container_name: gpt-sovits
        environment:
            - is_half=False
            - is_share=False
            - gpt_path=/gpt-sovits-data/GPT_weights/xiaote.ckpt
            - sovits_path=/gpt-sovits-data/SoVITS_weights/xiaote.pth
            - cnhubert_path=GPT_SoVITS/pretrained_models/chinese-hubert-base
            - bert_path=GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
        volumes:
            - ./gpt-sovits:/gpt-sovits-data
            - gpt-sovits-cpu-data-output:/workspace/output
            - gpt-sovits-cpu-data-logs:/workspace/logs
            - gpt-sovits-cpu-data-reference:/workspace/reference
        working_dir: /workspace
        ports:
            - "9872:9872"
        shm_size: 16G
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: "all"
                          capabilities: [gpu]
        stdin_open: true
        tty: true
        command: ["python", "GPT_SoVITS/inference_webui.py", "zh"]
        restart: unless-stopped
    middleapi:
        build: 
            context: ./middleapi/
            dockerfile: Dockerfile
        container_name: middleapi
        ports:
            - "8000:8000"
        depends_on:
            - openweb-ui
            - gpt-sovits
        restart: unless-stopped
volumes:
    gpt-sovits-data-output: {}
    gpt-sovits-data-logs: {}
    gpt-sovits-data-reference: {}
