cutting:
  radio_component: Slice by Chinese punct
global:
  use_new_api: true
gpt:
  temperature: 1
  top_k: 5
  top_p: 1
reference:
  no_reference_mode: false
  reference_audio: https://torappu.prts.wiki/assets/audio/voice/char_4134_cetsyr/cn_029.wav?filename=%E5%AE%8C%E6%88%90%E9%AB%98%E9%9A%BE%E8%A1%8C%E5%8A%A8.wav
  reference_audio_language: Japanese
  reference_audio_text: いつかきっと、私たちが炎を点し、朽ち果てる全てを燃やし尽くせる日はやってくるわ。
