cutting:
  radio_component: Slice once every 4 sentences
global:
  use_new_api: true
gpt:
  temperature: 0.25
  top_k: 1
  top_p: 0
reference:
  no_reference_mode: false
  reference_audio: https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1739002890857/audio.wav
  reference_audio_language: Chinese
  reference_audio_text: 阿米娅看上去还是这么瘦弱，这个年纪的孩子，个子是不是应该更高一点才对？她到底有没有好好吃饭呢。
