# Test your FastAPI endpoints

POST http://127.0.0.1:8000/app/getconfig
Content-Type: application/json
Accept: application/json

{
    "section":"reference",
    "key":"reference_audio"
}

###
POST http://127.0.0.1:8000/app/setconfig
Content-Type: application/json
Accept: application/json

{
    "section":"gpt",
    "key":"top_k", 
    "value": 1
}

###
